### PR TITLE
set discovery.type if defined as ec2

### LINKED ISSUE #10: discovery.type needs to be set to ec2
according to my tests, the discovery only works if this aditional setting is added to the settings object before creating the node client

### PR DESCRIPTION
**Pull request by jsvd**
fixes #10

### CODE REVIEW

**Comment by suyograo** [comment]
LGTM

**Comment by suyograo** [comment]
Can we open an issue to add integration tests to these?

**Comment by jsvd** [comment]
opened issue :) https://github.com/logstash-plugins/logstash-output-elasticsearch-ec2/issues/13

**Comment by colinsurprenant** [comment]
LGTM - not tested

**Pull request closed without merging**
